version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: chat
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw" ]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data: